version: "3.5"
volumes:
  postgres-data:
services:
  vvarbot:
    build: ./
    volumes:
      - .:/home/app/vvarbot
      - ./node_modules:/home/node_modules
    command: yarn start
    # docker-compose run vvarbot yarn | -> for updating deps
