name: Build'n'Deploy

on:
  push:
    branches:    
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build, Tag, Push
        uses: mattdavis0351/actions/docker-gpr@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: vvarbot
          dockerfile-location: ./
      - name: Stop running VVARBOT on Droplet, if running
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: yarn pm2-stop --cwd ${{ secrets.REMOTE_TARGET }} || true
      - name: Deploy new code to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "./"
          target: ${{ secrets.REMOTE_TARGET }}
      - name:  Install any new deps and run VVARBOT
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: node -v && yarn --cwd ${{ secrets.REMOTE_TARGET }} && yarn --cwd ${{ secrets.REMOTE_TARGET }} pm2-start